name: Build and Commit

on:
  push:
    branches:
      - main

jobs:
  build-and-commit:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Commit and push dist files
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
          git add dist/
          git diff --cached --quiet || git commit -m "chore: update dist build [skip ci]"
          git push
